Repository kubernetes-csi/external-resizer, pull requests merged in 2019-04, with the labels that each got.

#32 remove permissions to endpoints for example RBAC
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 Update readme and update changelog
  CHANGELOG-0.1.0.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#33 Removed unused variable
  deploy/kubernetes/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M
