Repository kubernetes-csi/external-resizer, pull requests merged in 2019-03, with the labels that each got.

#17 Add release tools
  Dockerfile
  Makefile
  csi-release-tools/CONTRIBUTING.md
  csi-release-tools/LICENSE
  csi-release-tools/OWNERS
  csi-release-tools/README.md
  csi-release-tools/RELEASE.md
  csi-release-tools/SECURITY_CONTACTS
  csi-release-tools/build.make
  csi-release-tools/code-of-conduct.md
  csi-release-tools/travis.yml
  csi-release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#16 add example YAMLs for deploying external-resizer
  deploy/kubernetes/deployment.yaml
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#18 fix release tools
  .travis.yml
  Makefile
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/build.make
  release-tools/code-of-conduct.md
  release-tools/travis.yml
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#23 relax release tools check
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#20 Update README about resizer being alpha quality
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#25 Add version flag
  cmd/csi-resizer/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#27 Use distroless as base image
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 use a unique leader lock name
  cmd/csi-resizer/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#30 Fix deploy example images url
  deploy/kubernetes/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
