Repository kubernetes-csi/external-resizer, pull requests merged in 2020-12, with the labels that each got.

#128 Bump Klog dependency to v2
  cmd/csi-resizer/main.go
  go.mod
  pkg/controller/controller.go
  pkg/resizer/csi_resizer.go
  pkg/resizer/trivial_resizer.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#129 Bumping csi-lib-utils to 0.9.0
  README.md
  cmd/csi-resizer/main.go
  deploy/kubernetes/deployment.yaml
  go.mod
  go.sum
  pkg/controller/controller_test.go
  pkg/resizer/csi_resizer.go
  pkg/resizer/csi_resizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#134 Add Changelog for 1.1
  CHANGELOG-1.1.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
