Repository kubernetes-csi/external-resizer, pull requests merged in 2020-10, with the labels that each got.

#106 Upgrade csi-lib-utils to 0.8.1
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#107 Upgrade csi-lib-utils to 0.8.1
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#109 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#110 release-0.5: update release-tools
  go.mod
  go.sum
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#111 release-1.0: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#112 Add change log for 0.5.1 release
  CHANGELOG-0.5.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#115 Create v1.0.1 change log
  CHANGELOG-1.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#116 Fix the failing multiarch builds
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#118 Cherry-pick #116: Fix the failing multiarch builds
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#120 Revert to multiarch distroless base image
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#122 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
