Repository kubernetes-csi/external-resizer, pull requests merged in 2020-08, with the labels that each got.

#94 bump csi-translation-lib to include vSphere volume translation
  go.mod
  go.sum
  pkg/resizer/csi_resizer.go
  pkg/resizer/trivial_resizer.go
  vendor/k8s.io/csi-translation-lib/CONTRIBUTING.md
  vendor/k8s.io/csi-translation-lib/OWNERS
  vendor/k8s.io/csi-translation-lib/SECURITY_CONTACTS
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/csi-translation-lib/plugins/vsphere_volume.go
  vendor/k8s.io/csi-translation-lib/translate.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/XXL

#82 Replace `csiTimeout` to `timeout` param for resizer
  README.md
  cmd/csi-resizer/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#98 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#99 Update release 1.0 branch
  README.md
  cmd/csi-resizer/main.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/csi/mock_client.go
  pkg/util/util.go
  pkg/util/util_test.go
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/storage, size/L

#100 Bump go version to 1.15
  go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#101 Bump kube dependencies to v1.19.0
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/lifecycle.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#102 rebase 1.0 branch with master
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/lifecycle.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
