Repository kubernetes-csi/external-resizer, pull requests merged in 2021-08, with the labels that each got.

#165 Update k8s dependencies to v1.22.0
  README.md
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, sig/storage, size/L

#151 Map PV access modes to CSI access modes based on driver capability
  go.mod
  go.sum
  pkg/controller/controller_test.go
  pkg/csi/client.go
  pkg/csi/mock_client.go
  pkg/resizer/csi_resizer.go
  pkg/resizer/csi_resizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/accessmodes/access_modes.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#164 release-1.1: update release-tools
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, lgtm, release-note-none, size/L, cncf-cla: yes

#169 Add changelog for 1.3 release
  CHANGELOG/CHANGELOG-1.3.md
Labels: approved, lgtm, release-note-none, size/L, cncf-cla: yes
