Repository kubernetes-csi/external-resizer, pull requests merged in 2022-12, with the labels that each got.

#246 Fix panic if unable to update PVC
  pkg/controller/resize_status.go
Labels: approved, lgtm, release-note, cncf-cla: yes, size/XS

#247 Update dependency go modules for k8s v1.26.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/XL, cncf-cla: yes

#248 Upgrade csi-lib-utils to v0.12.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, kind/cleanup, release-note-none, size/L, cncf-cla: yes

#249 Add CHANGELOG-1.7md for k8s 1.26.0 release
  CHANGELOG/CHANGELOG-1.7.md
Labels: approved, lgtm, release-note-none, size/L, kind/documentation, cncf-cla: yes
