Repository kubernetes-csi/external-resizer, pull requests merged in 2022-04, with the labels that each got.

#199 [Backoport][release-1.2] Fix: PVC used by a job doesn't get resize after the pod of the job completed
  pkg/controller/controller.go
Labels: kind/bug, approved, lgtm, release-note-none, ok-to-test, cncf-cla: yes, size/XS

#200 [Backport][release-1.3] Fix: PVC used by a job doesn't get resize after the pod of the job completed
  pkg/controller/controller.go
Labels: kind/bug, approved, lgtm, release-note-none, ok-to-test, cncf-cla: yes, size/XS

#202 Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L, cncf-cla: yes

#201 master: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: approved, lgtm, release-note-none, cncf-cla: yes, size/XS

#203 rbac: remove unwanted rbac for leader election
  deploy/kubernetes/rbac.yaml
Labels: approved, lgtm, kind/cleanup, release-note-none, cncf-cla: yes, size/XS
