Repository kubernetes-csi/external-resizer, pull requests merged in 2024-07, with the labels that each got.

#419 Skip modifying volumes owned by other CSI drivers
  pkg/modifycontroller/controller.go
Labels: kind/bug, approved, lgtm, release-note, cncf-cla: yes, size/XS

#421 clear modify status when the operation is completed
  pkg/modifycontroller/modify_status.go
  pkg/modifycontroller/modify_status_test.go
  pkg/modifycontroller/modify_volume_test.go
Labels: kind/bug, approved, lgtm, release-note, size/M, cncf-cla: yes

#424 Changelog for v1.11.2
  CHANGELOG/CHANGELOG-1.11.md
Labels: approved, lgtm, release-note-none, cncf-cla: yes, size/S
