Repository kubernetes-csi/external-resizer, pull requests merged in 2024-08, with the labels that each got.

#429 Promote VolumeAttributesClass to Beta
  README.md
  pkg/features/features.go
Labels: approved, lgtm, release-note, kind/documentation, cncf-cla: yes, size/S

#431 Bump release tools
  release-tools/.github/dependabot.yaml
  release-tools/.github/workflows/codespell.yml
  release-tools/.github/workflows/trivy.yaml
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/generate-patch-release-notes.sh
  release-tools/prow.sh
Labels: approved, lgtm, kind/cleanup, release-note-none, size/M, cncf-cla: yes

#432 Bump VAC objects to v1beta1
  pkg/modifycontroller/controller.go
  pkg/modifycontroller/controller_test.go
  pkg/modifycontroller/modify_status_test.go
  pkg/modifycontroller/modify_volume.go
  pkg/modifycontroller/modify_volume_test.go
Labels: approved, lgtm, kind/cleanup, size/M, cncf-cla: yes, release-note-action-required

#433 util/slowset: fix data race
  pkg/util/slowset.go
Labels: kind/bug, approved, lgtm, kind/failing-test, release-note-none, ok-to-test, cncf-cla: yes, size/S

#435 Add changelog for v1.12
  CHANGELOG/CHANGELOG-1.12.md
  README.md
Labels: approved, lgtm, release-note-none, size/L, cncf-cla: yes
