Repository kubernetes-csi/external-resizer, pull requests merged in 2024-01, with the labels that each got.

#356 resizer does not depend on informer
  cmd/csi-resizer/main.go
  pkg/controller/controller_test.go
  pkg/controller/expand_and_recover_test.go
  pkg/controller/resize_status_test.go
  pkg/resizer/csi_resizer.go
  pkg/resizer/csi_resizer_test.go
Labels: approved, lgtm, kind/cleanup, release-note-none, size/M, ok-to-test, cncf-cla: yes

#351 Add Modify Volume Support
  README.md
  cmd/csi-resizer/main.go
  deploy/kubernetes/rbac.yaml
  go.mod
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/expand_and_recover.go
  pkg/controller/expand_and_recover_test.go
  pkg/controller/resize_status.go
  pkg/controller/resize_status_test.go
  pkg/csi/client.go
  pkg/csi/mock_client.go
  pkg/features/features.go
  pkg/modifier/csi_modifier.go
  pkg/modifier/csi_modifier_test.go
  pkg/modifier/modifier.go
  pkg/modifycontroller/controller.go
  pkg/modifycontroller/controller_test.go
  pkg/modifycontroller/modify_status.go
  pkg/modifycontroller/modify_status_test.go
  pkg/modifycontroller/modify_volume.go
  pkg/modifycontroller/modify_volume_test.go
  pkg/resizer/csi_resizer_test.go
  pkg/resizer/trivial_resizer.go
  pkg/testutil/test_util.go
  pkg/util/events.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/feature, size/XXL, approved, lgtm, release-note, cncf-cla: yes

#368 Add changelog for v1.10.0
  CHANGELOG/CHANGELOG-1.10.md
Labels: approved, lgtm, release-note-none, size/L, kind/documentation, cncf-cla: yes

#369 Update Feature Status in README
  README.md
Labels: approved, lgtm, release-note-none, kind/documentation, cncf-cla: yes, size/XS
