Repository kubernetes-csi/external-resizer, pull requests merged in 2024-03, with the labels that each got.

#379 [release-1.9] Update release tools with go version fix
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/generate_patch_release_notes.sh
  release-tools/go-modules-update.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: approved, lgtm, kind/cleanup, size/L, release-note, ok-to-test, cncf-cla: yes

#380 Changelog for v1.9.4
  CHANGELOG/CHANGELOG-1.9.md
Labels: approved, lgtm, release-note-none, cncf-cla: yes, size/S

#382 Changelog for v1.10.1
  CHANGELOG/CHANGELOG-1.10.md
Labels: approved, lgtm, release-note-none, cncf-cla: yes, size/S

#375 Fix modifycontroller nil pointer dereference
  pkg/modifycontroller/controller.go
Labels: kind/bug, approved, lgtm, release-note, ok-to-test, cncf-cla: yes, size/XS
