Repository kubernetes-csi/external-resizer, pull requests merged in 2025-01, with the labels that each got.

#459 Move recover beta new
  .prow.sh
  README.md
  pkg/controller/expand_and_recover.go
  pkg/features/features.go
Labels: approved, lgtm, release-note, size/M, cncf-cla: yes

#453 Ensure infeasible PVC modifications are retried at slower pace
  cmd/csi-resizer/main.go
  pkg/csi/mock_client.go
  pkg/modifycontroller/controller.go
  pkg/modifycontroller/controller_test.go
  pkg/modifycontroller/modify_status.go
  pkg/modifycontroller/modify_status_test.go
  pkg/modifycontroller/modify_volume.go
  pkg/modifycontroller/modify_volume_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note, cncf-cla: yes

#464 Bump release tools and fix a typo in github URL
  CHANGELOG/CHANGELOG-1.13.md
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, lgtm, release-note-none, cncf-cla: yes, size/XS
